// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Collections: typeof import('./src/components/Collections.vue')['default']
    Filters: typeof import('./src/components/Filters.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
